spring.application.name=meu-novo-ms
spring.datasource.username=user_meunovo_ms
spring.datasource.password=Ch77230981@@@
spring.datasource.url=jdbc:mysql://192.168.1.10:3306/projeto_pessoal_ms
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true